import sqlite3
import datetime

class PatientDatabase:
    def __init__(self):
        self.patient_db_name = "patients"

    #{{{ create_patient_db

    def create_patient_db(self):
        con = sqlite3.connect(self.patient_db_name)
        return con

    # }}}

    # {{{ create_table_detail

    def create_table_detail(self):
        '''
        This method will create a table "detail" if does not exist.
        '''
        # connection
        con = self.create_patient_db()
        # cursor
        cur = con.cursor()

        # create table "details" if does not exist
        # columns are
        # name - name of the patient
        # dob - date of birth of patient
        # dov - date of vaccination of the zeroth dose
        # phone - phone number of the patient
        cur.execute(""" CREATE TABLE if not exists detail(
                                                            patientid integer primary key,
                                                            name text,
                                                            dob text,
                                                            dov text,
                                                            phone text
                                                            )"""
                    )

        # save
        con.commit()
        con.close()

    # }}}

    #{{{ insert_in_table_detail

    def insert_in_table_detail(self, name, dob, dov, phone):
        # create table if does not exist
        self.create_table_detail()

        # connection
        con = self.create_patient_db()

        # cursor
        cur = con.cursor()
        
        # data to be inserted into table "detail"
        data = [name, dob, dov,phone]

        # insert in table "details"
        # in python sqlite3 if a autogenerated integer is to be added automatically,
        # then "NULL" should be used for that column
        cur.execute(" INSERT INTO detail values(NULL, ?, ? , ?, ?)", data )

        con.commit()
        con.close()
        print("I am inside insert_in_table_detail")
        
        # lets return the id of the last row that was inserted
        return (cur.lastrowid)
    # }}}

    #{{{ display_from_table_detail 

    def display_from_table_detail(self):

        # connection
        con = self.create_patient_db()

        # cursor
        cur = con.cursor()

        res = cur.execute("SELECT name from detail")
        records = res.fetchall()

        con.close()

        return records


    # }}}

    # {{{ create_table_vacdates 
    def create_table_vacdates(self):

        '''
        This method will create a table "vacdates" if does not exist.
        See below for table columns

        Eg table 
        | id    |   date        | messagestatus     | foreignkey    |
        | 1     |   23-1-2023   |   1               | 1             |
        '''
        # connection
        con = self.create_patient_db()
        # cursor
        cur = con.cursor()

        # create table "vacdates" if does not exist
        # table columns
        # id primary key
        # date - future date of vaccination
        # messagestatus - wheather sms is sent or not 
        #               0 - sms not yet sent
        #               1 - sms sent
        # foreign key  - relation with table "detail"
        cur.execute(""" CREATE TABLE if not exists vacdates(
                                                            id integer primary key,
                                                            date text,
                                                            messagestatus integer,
                                                            patientid integer,
                                                            foreign key (patientid) REFERENCES detail (patientid)
                                                            )"""
                    )
        # here patientid in "vacdates" table is a column of child key this references the primary key in table "detail"

        # save
        con.commit()
        con.close()
    # }}}

    # {{{ insert_in_table_vacdates 

    def insert_in_table_vacdates(self, patient_id):
        '''
        This method is given the patient_id which will reference a row of this table
        to the row of the table "detail"
        "calc_vac_dates" and the dates returned by that fucntion will be used here.
        '''
        # create table if does not exist
        self.create_table_vacdates()

        # connection
        con = self.create_patient_db()

        # cursor
        cur = con.cursor()

        # calculate the future dates
        dates = self.calc_vac_dates()
        
        for i in dates:
            # data to be inserted into table "vacdates"
            data = [i, 0, patient_id]

            # insert in table "details"
            cur.execute("INSERT INTO vacdates values(NULL, ?, ?, ?)", data )

        con.commit()
        con.close()
        print("I am inside insert_in_table_vacdates")

    # }}}

    # {{{ calc_vac_dates

    def calc_vac_dates(self):
        '''
        This function shall calculate the future dates of rabies vaccination 
        Assumption: today is the zeroth day
        '''
        zeroth_day = datetime.date.today()

        dates = []

        time_interval = [3,7,14,30]
        
        for i in time_interval:
            #Calculate the dates of the nth time_interval
            day_n = zeroth_day + datetime.timedelta(days=i)

            #Append the future date to dates
            dates.append(day_n)

        print("I am inside patient_database.calc_vac_dates")
        print(dates)
        return dates
        


    # }}}
    
    # {{{ display_from_table_vacdates

    def display_from_table_vacdates(self):

        # connection
        con = self.create_patient_db()

        # cursor
        cur = con.cursor()

        # reference from "https://realpython.com/python-sql-libraries/#join"
        try:
            res = cur.execute(
                "SELECT detail.name, detail.phone from vacdates INNER JOIN detail ON vacdates.patientid = detail.patientid"
            )
            records = res.fetchall()

            con.close()

            return records
        except:
            return []
    # }}}

    # {{{ display from table vacdates on a particular date 
    def display_from_table_vacdates_on_a_date(self, date):

        # connection
        con = self.create_patient_db()

        # cursor
        cur = con.cursor()

        res = cur.execute(
            "SELECT detail.name, detail.phone from vacdates INNER JOIN detail ON vacdates.patientid = detail.patientid WHERE date=(?)",[date]
        )
        records = res.fetchall()

        con.close()

        return records

    # }}}
